name: flutter_alert
description: Flutter package which shows a crossplatform alert messages on Android (Material) and iOS (Cupertino).
version: 0.4.0
homepage: https://github.com/jerolimov/flutter_alert

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
